net: dwc_eth_qos: fix eqos_get_interface_rzv2h signature
The .interface op expects a 'const struct udevice *' argument. Make
eqos_get_interface_rzv2h match it to fix an incompatible-pointer-type
error with newer (GCC 15) toolchains:

`drivers/net/dwc_eth_qos.c:1521:22: error: initialization of ‘phy_interface_t (*)(const struct udevice *)’ from incompatible pointer type ‘phy_interface_t (*)(struct udevice *)’ [-Wincompatible-pointer-types]`